### ISSUE TITLE
MSVC2017 15.4.1 build failure

### ISSUE THREAD

**Issue by Ghosthree3** [xmrig/xmrig-nvidia#32]
Trying to build with the latest release of MSVC2017 (15.4.1) causes the following error,
`LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'`
I noticed on the release page for xmrig-deps it says, "msvc2017 libs now compatible only with Visual Studio 2017 version 15.3, use Visual Studio Installer to upgrade."
I'm assuming that the deps were built with 15.3 (20150812?) and are not compatible with people using the latest release.
Is there any way around this without either downgrading or building the deps personally?

MSVC2015 builds fine, fortunately.

**Comment by xmrig** [comment]
MSVC Community 2017 v15.4.2 works fine, checked it now.

If MSVC2015 builds work fine with your MSVC2017, it meant version below v15.3.
Thank you.

**Comment by xmrig** [comment]
Oh I forgot about `-T v140,host=x64` part when run cmake, so it correct use MSVC2015 libs.
I updated docs. Thank you.

**Comment by KHouse75** [comment]
I have the same problem:  LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'
I use -T v140,host=x64 when running cmake.

I was originally running MSVC2017 15.4.1.  Installed the latest update to 15.4.3 but the problem persists.

**Comment by xmrig** [comment]
Possible for CUDA9 builds don't need specify `-T v140,host=x64` and you can use 2017 libs, otherwise you need use 2015 libs.
Thank you.

**Comment by kevinjourdain** [comment]
I am still having the same problem... I tried recompiling libuv too... What can I do? I have cuda9.1 and VS2017 15.5.1...
